import { useState, useRef } from "react";
import { AnimatePresence, motion } from "framer-motion";
import { Download, Volume2, VolumeX, Loader } from "lucide-react";
import { jsPDF } from "jspdf";
import Stage0 from "./components/Stage0";
import Stage1 from "./components/Stage1";
import Stage2 from "./components/Stage2";
import Stage3 from "./components/Stage3";
import Stage4 from "./components/Stage4";
import Stage5 from "./components/Stage5";

const downloadPDF = ({ situation, preparation, empathy, phrasing }) => {
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  const W = doc.internal.pageSize.getWidth();
  const margin = 20;
  const contentW = W - margin * 2;
  const accent = [214, 107, 109];
  const dark = [90, 58, 59];
  const muted = [160, 112, 112];
  const bg = [244, 237, 232];

  let y = 0;

  const checkPage = (needed = 10) => {
    if (y + needed > doc.internal.pageSize.getHeight() - margin) {
      doc.addPage();
      y = margin;
    }
  };

  const drawSectionLabel = (label, sublabel) => {
    checkPage(14);
    doc.setFontSize(7);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(...accent);
    doc.text(label.toUpperCase(), margin, y);
    if (sublabel) {
      doc.setFont("helvetica", "normal");
      doc.setTextColor(...muted);
      doc.text(sublabel, margin, y + 4.5);
      y += 9;
    } else {
      y += 5;
    }
  };

  const drawBlock = (labelText, bodyText, highlighted = false) => {
    if (!bodyText) return;
    const lines = doc.splitTextToSize(bodyText, contentW - 8);
    const blockH = 6 + lines.length * 5 + 4;
    checkPage(blockH + 4);

    if (highlighted) {
      doc.setFillColor(244, 225, 225);
      doc.setDrawColor(...accent);
      doc.setLineWidth(0.4);
      doc.roundedRect(margin, y, contentW, blockH, 3, 3, "FD");
    } else {
      doc.setFillColor(...bg);
      doc.setDrawColor(...bg);
      doc.roundedRect(margin, y, contentW, blockH, 3, 3, "F");
    }

    doc.setFontSize(7);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(...(highlighted ? accent : muted));
    doc.text(labelText.toUpperCase(), margin + 4, y + 5);

    doc.setFontSize(9);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(...dark);
    doc.text(lines, margin + 4, y + 10);

    y += blockH + 3;
  };

  // Header
  doc.setFillColor(...accent);
  doc.rect(0, 0, W, 28, "F");
  doc.setFontSize(18);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(244, 237, 232);
  doc.text("Your Conversation Plan", margin, 17);
  doc.setFontSize(8);
  doc.setFont("helvetica", "normal");
  doc.text("rabbithole.app", W - margin, 17, { align: "right" });
  y = 36;

  // Pillar 1
  drawSectionLabel("Pillar 1", "Core Needs");
  drawBlock("Core Issue", preparation.coreIssue, true);
  drawBlock("Your Goal", preparation.goal);
  drawBlock("Desired Outcome", preparation.outcome);
  y += 4;

  // Pillar 2
  drawSectionLabel("Pillar 2", "Strategy");
  drawBlock("Their Side", empathy.perspective, true);
  if (empathy.tone) {
    const toneDesc =
      empathy.tone === "gentle"
        ? "Soft, easing in slowly"
        : empathy.tone === "direct"
          ? "Clear and straightforward"
          : "Open, seeking to understand";
    drawBlock(
      "Tone",
      `${empathy.tone.charAt(0).toUpperCase() + empathy.tone.slice(1)} — ${toneDesc}`,
    );
  }
  if (empathy.emotions?.length)
    drawBlock("Emotions to Bring", empathy.emotions.join(" · "));
  const feelingVal = Array.isArray(situation.feeling)
    ? situation.feeling.join(" · ")
    : situation.feeling;
  if (feelingVal) drawBlock("Going in Feeling", feelingVal);
  y += 4;

  // Pillar 3
  drawSectionLabel("Pillar 3", "Your Openers");
  if (phrasing.instinct)
    drawBlock("Your Instinct Was", `"${phrasing.instinct}"`);
  if (phrasing.iStatementText)
    drawBlock("I-statement", `"${phrasing.iStatementText}"`, true);
  if (phrasing.gottmanText)
    drawBlock("Soft Opening", `"${phrasing.gottmanText}"`, true);
  if (phrasing.framingText)
    drawBlock("Framing", `"${phrasing.framingText}"`, true);

  // Footer
  const pageH = doc.internal.pageSize.getHeight();
  doc.setDrawColor(...accent);
  doc.setLineWidth(0.3);
  doc.line(margin, pageH - 12, W - margin, pageH - 12);
  doc.setFontSize(7);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(...muted);
  doc.text("Generated by RabbitHole · rabbithole.app", margin, pageH - 7);
  doc.text(new Date().toLocaleDateString(), W - margin, pageH - 7, {
    align: "right",
  });

  doc.save("conversation-plan.pdf");
};

const SpeakerButton = ({ panelRef }) => {
  const [status, setStatus] = useState("idle"); // idle | loading | playing
  const audioRef = useRef(null);

  const toggle = async () => {
    if (status === "playing") {
      audioRef.current?.pause();
      audioRef.current = null;
      setStatus("idle");
      return;
    }

    if (!panelRef.current) return;

    const BLOCK_TAGS = new Set([
      "DIV", "P", "H1", "H2", "H3", "H4", "H5", "H6",
      "LI", "TR", "TD", "TH", "SECTION", "ARTICLE", "HEADER",
      "FOOTER", "BLOCKQUOTE", "LABEL", "SPAN",
    ]);

    const extractText = (node) => {
      if (node.nodeType === Node.TEXT_NODE) {
        return node.textContent;
      }

      if (node.nodeType !== Node.ELEMENT_NODE) return "";

      const tag = node.tagName;

      // Replace inputs/textareas with their value or placeholder
      if (tag === "TEXTAREA" || tag === "INPUT") {
        const val = node.value?.trim();
        const ph = node.placeholder?.trim();
        return (val || ph || "") + ". ";
      }

      // Skip SVGs entirely
      if (tag === "SVG" || tag === "svg") return "";

      // Skip navigation/action buttons (Back, Continue, →, etc.) but read option buttons
      if (tag === "BUTTON") {
        const btnText = node.textContent?.trim() ?? "";
        // Short action words or arrow-only buttons are navigation — skip them
        const isNavButton = /^(←|→|back|continue|save|cancel|that'?s right|let me adjust|dive in|dig (in|deeper)|see how|see the bigger picture|add your own)/i.test(btnText);
        if (isNavButton) return "";
        // Otherwise it's an option pill — read it as a list item
        return btnText + ". ";
      }

      let inner = "";
      for (const child of node.childNodes) {
        inner += extractText(child);
      }

      // After block-level elements, ensure a sentence break
      if (BLOCK_TAGS.has(tag)) {
        const trimmed = inner.trim();
        if (!trimmed) return "";
        // Add ". " if doesn't already end with sentence-ending punctuation
        return trimmed.match(/[.!?]$/) ? trimmed + " " : trimmed + ". ";
      }

      return inner;
    };

    const text = extractText(panelRef.current).replace(/\.\s*\.\s*/g, ". ").replace(/\s{2,}/g, " ").trim();
    if (!text) return;

    setStatus("loading");
    try {
      const response = await fetch("/api/speak", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ text }),
      });

      if (!response.ok) throw new Error("TTS failed");

      const blob = await response.blob();
      const url = URL.createObjectURL(blob);
      const audio = new Audio(url);
      audioRef.current = audio;

      audio.onended = () => {
        URL.revokeObjectURL(url);
        audioRef.current = null;
        setStatus("idle");
      };

      audio.play();
      setStatus("playing");
    } catch (err) {
      console.error("TTS error:", err);
      setStatus("idle");
    }
  };

  return (
    <button
      onClick={toggle}
      title={status === "playing" ? "Stop reading" : "Read instructions aloud"}
      className="absolute -top-4 -right-4 z-20 p-2.5 rounded-full bg-primary hover:bg-primary-hover transition-all duration-300 text-white shadow-lg shadow-primary/30">
      {status === "loading" ? (
        <Loader size={18} className="animate-spin" />
      ) : status === "playing" ? (
        <VolumeX size={18} />
      ) : (
        <Volume2 size={18} />
      )}
    </button>
  );
};

const TOTAL_STAGES = 6;
// How far into the image to travel per stage (0–1). 0.75 = 75% of image height used total.
const BG_TRAVEL = 0.9;

function App() {
  const [stage, setStage] = useState(0);
  const [stageData, setStageData] = useState({
    initialInput: "",
    situation: {},
    preparation: {},
    empathy: {},
    phrasing: {},
  });

  // Points to the rendered panel DOM node — read by SpeakerButton via .innerText
  const panelRef = useRef(null);

  const advanceTo = (nextStage, newData = {}) => {
    setStageData((prev) => ({ ...prev, ...newData }));
    setStage(nextStage);
  };

  const goBack = () => setStage((prev) => Math.max(0, prev - 1));

  // Background pans from 0% to BG_TRAVEL*100% as stages progress
  const bgY = (stage / TOTAL_STAGES) * BG_TRAVEL * 100;

  return (
    <div
      className="min-h-screen w-screen overflow-y-auto flex items-start sm:items-center justify-center p-4 pt-14 sm:pt-4"
      style={{
        backgroundImage: "url(/background.png)",
        backgroundSize: "cover",
        backgroundPosition: `center ${bgY}%`,
        backgroundRepeat: "no-repeat",
        transition: "background-position 1s ease-in-out",
      }}>

      {/* Mobile progress — horizontal dots across the top */}
      <div className="sm:hidden fixed top-3 left-1/2 -translate-x-1/2 flex flex-row gap-3 z-50 items-center">
        {[1, 2, 3, 4, 5, 6].map((s) => (
          <div key={s} className="relative flex items-center justify-center">
            {stage === s || (stage === 0 && s === 1) ? (
              <div className="w-2 h-2 rounded-full bg-primary shadow-lg shadow-primary/40" />
            ) : (
              <div
                className={`rounded-full transition-all duration-500 ${stage > s ? "w-2 h-2 bg-primary-hover" : "w-1.5 h-1.5 bg-white/30"}`}
              />
            )}
          </div>
        ))}
      </div>

      {/* Desktop progress — vertical bunny sidebar */}
      <div className="hidden sm:flex flex-col gap-5 z-50 items-center fixed right-6 top-1/2 -translate-y-1/2">
        {[1, 2, 3, 4, 5, 6].map((s) => (
          <div key={s} className="relative flex items-center justify-center">
            {stage === s || (stage === 0 && s === 1) ? (
              <img
                src="/rabbit.png"
                alt="current step"
                className="w-6 h-9 select-none"
                style={{
                  filter:
                    "drop-shadow(0 0 4px var(--color-black-60, rgba(0,0,0,0.6)))",
                }}
              />
            ) : (
              <div
                className={`w-5 h-5 rounded-full transition-all duration-500 ${stage > s ? "bg-primary-hover" : "bg-white/20"}`}
              />
            )}
          </div>
        ))}
      </div>

      {/* Single stage shown at a time, fades in/out */}
      <div className="max-w-4xl w-full relative z-10">
        <AnimatePresence mode="wait">
          {stage === 0 && (
            <motion.div
              key="s0"
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              exit={{ opacity: 0 }}
              transition={{ duration: 0.4 }}>
              <div className="text-center mb-10">
                <img
                  src="/logo.svg"
                  alt="RabbitHole"
                  className="mx-auto mb-10 h-25"
                />
                <p className="text-white/80 text-base tracking-widest uppercase font-figtree">
                  A guide for navigating difficult conversations
                </p>
              </div>
              <div className="relative">
                <SpeakerButton panelRef={panelRef} />
                <Stage0
                  ref={panelRef}
                  onComplete={(input) => advanceTo(1, { initialInput: input })}
                />
              </div>
            </motion.div>
          )}
          {stage === 1 && (
            <motion.div
              key="s1"
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              exit={{ opacity: 0 }}
              transition={{ duration: 0.4 }}>
              <div className="relative">
                <SpeakerButton panelRef={panelRef} />
                <Stage1
                  ref={panelRef}
                  stageData={stageData}
                  onComplete={(situation) => advanceTo(2, { situation })}
                  onBack={goBack}
                />
              </div>
            </motion.div>
          )}
          {stage === 2 && (
            <motion.div
              key="s2"
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              exit={{ opacity: 0 }}
              transition={{ duration: 0.4 }}>
              <div className="relative">
                <SpeakerButton panelRef={panelRef} />
                <Stage2
                  ref={panelRef}
                  stageData={stageData}
                  onComplete={(preparation) => advanceTo(3, { preparation })}
                  onBack={goBack}
                />
              </div>
            </motion.div>
          )}
          {stage === 3 && (
            <motion.div
              key="s3"
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              exit={{ opacity: 0 }}
              transition={{ duration: 0.4 }}>
              <div className="relative">
                <SpeakerButton panelRef={panelRef} />
                <Stage3
                  ref={panelRef}
                  stageData={stageData}
                  onComplete={(empathy) => advanceTo(4, { empathy })}
                  onBack={goBack}
                />
              </div>
            </motion.div>
          )}
          {stage === 4 && (
            <motion.div
              key="s4"
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              exit={{ opacity: 0 }}
              transition={{ duration: 0.4 }}>
              <div className="relative">
                <SpeakerButton panelRef={panelRef} />
                <Stage4
                  ref={panelRef}
                  stageData={stageData}
                  onComplete={(phrasing) => advanceTo(5, { phrasing })}
                  onBack={goBack}
                />
              </div>
            </motion.div>
          )}
          {stage === 5 && (
            <motion.div
              key="s5"
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              exit={{ opacity: 0 }}
              transition={{ duration: 0.4 }}>
              <div className="relative">
                <SpeakerButton panelRef={panelRef} />
                <Stage5
                  ref={panelRef}
                  stageData={stageData}
                  onBack={goBack}
                  onFinish={() => setStage(6)}
                />
              </div>
            </motion.div>
          )}
          {stage === 6 && (
            <motion.div
              key="s6"
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              exit={{ opacity: 0 }}
              transition={{ duration: 0.4 }}
              className="text-center">
              <img
                src="/logo.svg"
                alt="RabbitHole"
                className="mx-auto mb-10 h-25"
              />
              <p className="text-white/70 text-lg font-figtree mb-8">
                You've done the work. Now go have that conversation.
              </p>
              <button
                onClick={() => downloadPDF(stageData)}
                className="flex items-center gap-2 mx-auto mb-6 px-8 py-4 bg-primary text-white rounded-2xl text-base font-semibold hover:bg-primary-hover transition-all shadow-xl shadow-primary/20 font-figtree">
                <Download size={16} /> Save your plan as PDF
              </button>
              <button
                onClick={() => {
                  setStageData({
                    initialInput: "",
                    situation: {},
                    preparation: {},
                    empathy: {},
                    phrasing: {},
                  });
                  setStage(0);
                }}
                className="text-white/40 hover:text-white/70 text-base transition-colors underline underline-offset-4 font-figtree">
                Start another one
              </button>
            </motion.div>
          )}
        </AnimatePresence>
      </div>
    </div>
  );
}

export default App;
